### PR TITLE
fix: no no-implicit-end error on compensation activity

### LINKED ISSUE #140: `no-implicit-end` rule reports false positives
### Describe the Bug

The `no-implicit-end` rule reports false positives when compensations are modeled.

image

### Steps to Reproduce

1. Model compensation boundary event with compensation activity
2. Implicit end is reported twice

### Expected Behavior

No implicit end reported

### Environment

- Library version: 10.3.0

---

Slack conversation: https://camunda.slack.com/archives/C0693F1NFK5/p1723790917001139

### PR DESCRIPTION
**Pull request by abdul99ahad**
Closes #140

### Proposed Changes

- [ ] Compensation Activity and Event now don't show `no-implicit-error`

 

### Checklist

To ensure you provided everything we need to look at your PR:

* [ ] **Brief textual description** of the changes present
* [ ] **Visual demo** attached
* [ ] **Steps to try out** present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [ ] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

File: rules/no-implicit-end.js [hunk 1]
```diff
@@ -32,6 +44,14 @@ module.exports = function() {
       return false;
     }
 
+    if (is(node, 'bpmn:BoundaryEvent') && isCompensationEventDefinition(node)) {
```
Comment (philippfromme) [inline rules/no-implicit-end.js:47]: We still want to treat this as an implicit end like any other boundary event.

image

For comparison, timer boundary event with the implicit end error.

image

**Review by philippfromme — CHANGES_REQUESTED** [review]

File: rules/no-implicit-end.js [hunk 2]
```diff
@@ -17,6 +17,30 @@ module.exports = function() {
...
+    return eventDefinitions.length && eventDefinitions.every(
+      definition => is(definition, 'bpmn:CompensateEventDefinition')
+    );
+  }
+
+  function isConnectedToActivity(node) {
+    const parent = findParent(node, 'bpmn:Process');
+    const artifacts = parent.artifacts || [];
+    return artifacts.some((element) => {
+      return (
```
Comment (philippfromme) [inline rules/no-implicit-end.js:32]: We always want to use the `is` util unless there's a very good reason not to.

```javascript
const { is } = require('bpmnlint-utils');

...

return is(element, 'bpmn:Association') && is(element.sourceRef, 'bpmn:BoundaryEvent') && element.sourceRef.get('id') === node.get('id');
```

File: rules/no-implicit-end.js [hunk 3]
```diff
@@ -48,3 +82,21 @@ module.exports = function() {
 
   return { check };
 };
+
+function findParent(node, type) {
```
Comment (philippfromme) [inline rules/no-implicit-end.js:86]: Let's add this function to the utils and import it.

File: rules/no-implicit-end.js [hunk 4]
```diff
@@ -17,6 +17,30 @@ module.exports = function() {
     );
   }
 
+  function isCompensationEventDefinition(node) {
```
Comment (philippfromme) [inline rules/no-implicit-end.js:20]: Suggestion: Rename to `isCompensationEvent`.

**Review by philippfromme — CHANGES_REQUESTED** [review]

**Review by philippfromme — APPROVED** [review]
Good job! Just added a couple of small adjustments.
